# .streamlit/secrets.toml
# Replace these values with your actual Upstox API credentials.
# Do NOT commit this file to version control.

UPSTOX_API_KEY =c87d335b-6840-4aa9-a2f7-3d702bfe80b5
UPSTOX_API_SECRET =j6hy0tforn
UPSTOX_REDIRECT_URI =http://localhost
